
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "D:/app/CMake/share/cmake-3.30/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt"
    message: |
      The system is: Windows - 10.0.26100 - AMD64
...
