//tealium universal tag - utag.221 ut4.0.202501072049, Copyright 2025 Tealium.com Inc. All Rights Reserved.
window._da_=window._da_||[];try{(function(id,loader){var u={};utag.o[loader].sender[id]=u;if(utag===undefined){utag={};}if(utag.ut===undefined){utag.ut={};}if(utag.ut.loader===undefined){u.loader=function(o){var a,b,c,l;a=document;if(o.type==="iframe"){b=a.createElement("iframe");b.setAttribute("height","1");b.setAttribute("width","1");b.setAttribute("style","display:none");b.setAttribute("src",o.src);}else if(o.type==="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";b.src=o.src;}if(o.id){b.id=o.id;}if(typeof o.cb==="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb();},false);}else{b.onreadystatechange=function(){if(this.readyState==="complete"||this.readyState==="loaded"){this.onreadystatechange=null;o.cb();}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l==="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b);}}};}else{u.loader=utag.ut.loader;}
u.ev={"view":1,"link":1};u.initialized=false;u.map={"di_property_id":"da_propertyId"};u.extend=[function(a,b,c,d){c=['ga_term','ods_chapter','conversion_funnel','promo_id','tcContentGroup','store_order_line_type','lit_doc_type','lit_number','oct_cp_linkType','tcContentHierarchy4','lit_chapter','null_search_term','product_folder_name','sw_opn','clean_url','video_id','tcPageType','sw_folder_name','event_category','itemPosition','lit_section','oct_cp_compPosition','internal_campaigns','internal_campaign_source','itemID','solution_folder_name','download_file_name','tcLanguage','sampleCheckoutType','tcContentHierarchy1','datasheet_view','community_participation','internal_campaign_term','ga_campaign','designInputs','js_page.tooltype','event_label','tcContentHierarchy3','ga_content','ga_page_name','search_type','ti_design_type','cp.chipset','tcContentHierarchy2','search_term','oct_dc_topicType','distributor_name','oct_cp_rType','video_name','ga_source','tcSiteSubsection','referring_search_type','user_type','search_criteria','internal_campaign_content','ods_section','internal_campaign_medium','event_action','oct_cp_compGPN','oct_dc_menuClick','ev_exp_concat','statusBadge','oct_dc_displayType','tool_folder_name','avl_search_term','ga_medium','computer_id','js_page._metrics_store_data.checkout_method'];for(d=0;d<c.length;d++){try{b[c[d]]=b[c[d]]instanceof Array?b[c[d]]:b[c[d]]instanceof Object?b[c[d]]:b[c[d]].toString().toLowerCase()}catch(e){utag.DB(e);}}},function(a,b){try{if(1){if(b['ut.event']=="link"&&b.component_event){var path=null;if(typeof b.component_event.path!=="undefined"){path=b.component_event.path;}
if(!path&&typeof b.component_event.composedPath==="function"&&b.component_event.composedPath().length>0){path=b.component_event.composedPath();}
var link=null;var link_id=null;if(typeof b.component_event.target.getAttribute=="function"&&b.component_event.target.getAttribute("data-lid")){link_id=b.component_event.target.getAttribute("data-lid");}
if(b.component_event.currentTarget&&typeof b.component_event.currentTarget.getAttribute=="function"&&b.component_event.currentTarget.getAttribute("data-lid")){link_id=b.component_event.currentTarget.getAttribute("data-lid");}
if(path){for(var i=0;i<path.length;i++){if(path[i]!==window&&path[i].nodeName.indexOf("TI-")>-1){if(path[i].getAttribute('data-lid')){link_id=path[i].getAttribute('data-lid');break;}}}
if(path[0].localName=="a"){link=path[0];}
if(!link){for(var i=0;i<path.length;i++){if(path[i]!==window&&path[i].localName=="a"){link=path[i];break;}}}}else{if(b.component_event.target.localName=="a"){link=b.component_event.target;}}
if(/^vb\|.*/.test(link_id)){b.vBundleId=link_id.split('|')[1];link_id='vb';}
if(b.component_event.type=="tiMetricsAction"){if(typeof b.component_event.detail.error!=="undefined"&&b.component_event.detail.error.length>0){b.event_category='error';b.event_action=b.component_event.detail.eventName.toLowerCase();b.event_label=b.component_event.detail.error.toLowerCase();b.event_value='1';}else{if(b.component_event.detail.eventName=="radio select"){b.component_event.detail.elementName="ti-radio";}
if(!link_id&&b.component_event.detail.eventName){link_id=b.component_event.detail.elementName;if(/^vb\|.*/.test(link_id)){b.vBundleId=link_id.split('|')[1];link_id='vb';}}
if(b.component_event.detail.eventName=="custom component event"){var ga_mapping=b.component_event.detail.gaMapping;if(ga_mapping!==''&&ga_mapping!==undefined&&ga_mapping!==null){event_category=(ga_mapping["legacy-event-category"]===undefined)?"ti web component":ga_mapping["legacy-event-category"];event_action_id=(ga_mapping["legacy-event-action-id"]===undefined)?"":ga_mapping["legacy-event-action-id"]+" ";event_label_id=(ga_mapping["legacy-event-label-id"]===undefined)?"":ga_mapping["legacy-event-label-id"]+"|";b.event_category=ga_mapping["legacy-event-category"];b.event_action=event_action_id+b.component_event.detail.eventAction;b.event_label=event_label_id+b.component_event.detail.eventLabel;b.link_href=(ga_mapping['link_url']===undefined)?(b['link_href']||''):ga_mapping['link_url'];delete ga_mapping["legacy-event-action-id"];delete ga_mapping["legacy-event-label-id"];delete ga_mapping["legacy-event-category"];delete ga_mapping['link_url']
b.ga4_custom_mappings=ga_mapping;b.evt_standard='2024-emit_call'}
else{b.event_category="ti web component";b.event_action=b.component_event.detail.eventAction;b.event_label=b.component_event.detail.eventLabel;}}
if(b.component_event.detail.eventName=="add to cart"){b.event_category='store';b.event_action='add to cart';b.event_label=link_id+"|"+"add to cart|"+b.component_event.detail.data.ti_opn;b.event_value='1';b.custom_metric_value='55';b.events=['add to cart'];b.ecom_event='add';b.sampleCheckoutType=b.component_event.detail.data.part_type;b.ti_opn=b.component_event.detail.data.ti_opn;b.ti_gpn=b.component_event.detail.data.ti_gpn;b.avl_search_term=(b.component_event.detail.data.avl_search_term||'').toLowerCase();b._cprod=b._cprodname=[b.component_event.detail.data.ti_opn];b._cquan=[b.component_event.detail.data.part_quantity];b._cprice=[b.component_event.detail.data.part_unit_price];b._ccat=b.part_type=[b.component_event.detail.data.part_type.toUpperCase()];b._ccurrency=[b.component_event.detail.data.currency_code];b.cart_source=[b.component_event.detail.data.element_type];b.product_status=[b.component_event.detail.data.product_status];b.part_carrier=[b.component_event.detail.data.part_carrier];b.vBundleId=b.component_event.detail.data.vBundleId||'null';if(typeof b.component_event.detail.elementName!='undefined'){if(b.component_event.detail.elementName||''.toLowerCase().indexOf('samples')>-1){ti_addEvent(b,'samples add to cart');}}}
if(b.component_event.detail.eventName=="snackbar impression"){b.event_category="ti web component";b.event_action=b.component_event.detail.eventName;b.event_non_interaction=1;b.event_label=link_id;b.event_value='1';}
if(b.component_event.detail.eventName=="hover"){b.event_category="ti web component";b.event_action=b.component_event.detail.eventName;b.event_label=link_id+" "+b.component_event.detail.data.context;b.event_value='1';}
if(b.component_event.detail.eventName=="image click"){b.event_category="ti web component";b.event_action=b.component_event.detail.eventName;b.component_event.detail.data.column=b.component_event.detail.data.column=='image.jpg'?'video thumbnail':b.component_event.detail.data.column;b.event_label=link_id+" "+b.component_event.detail.data.value+" "+b.component_event.detail.data.column;b.event_value='1';}
if(b.component_event.detail.eventName=="scroll"){window.uniqueEvents=window.uniqueEvents||[];if(_isInArrayAlternative(uniqueEvents,u.id!=undefined&&u.id=='318'?b.component_event.detail.data.context+u.id:b.component_event.detail.data.context)==false){if(_isInArrayAlternative(uniqueEvents,b.component_event.detail.eventName)==false){uniqueEvents.push(b.component_event.detail.eventName);}
b.event_category="ti web component";b.event_action=b.component_event.detail.eventName;b.event_label=b.component_event.detail.data.context.replace(' ','|');b.event_value='1';uniqueEvents.push(b.component_event.detail.data.context);if(u.id!=undefined&&u.id=='318'){uniqueEvents.push(b.component_event.detail.data.context+u.id);}}}
if(b.component_event.detail.eventName=="click"||b.component_event.detail.eventName=="link click"){b.event_category="ti web component";b.event_action=b.component_event.detail.eventName;b.event_label=link_id+"|"+b.component_event.detail.data.value;b.clean_link_href=b.clean_link_href?b.clean_link_href:b.component_event.detail.data.url?b.component_event.detail.data.url:undefined;b.event_value='1';}
if(b.component_event.detail.eventName=="sort"){b.event_category="ti web component";b.event_action=b.component_event.detail.eventName;b.event_label=link_id+" "+b.component_event.detail.data.sortColumn+"|"+b.component_event.detail.data.sortDirection;b.event_value='1';}
if(b.component_event.detail.eventName=="tab click"){b.event_category="ti web component";b.event_action=b.component_event.detail.eventName;b.event_label=link_id+" "+b.component_event.detail.data.context.toLowerCase();b.event_value='1';if(b.component_event.detail.data.context=="dcof-ti-parts-tab"){b.event_label="dcof_material_search|parts";b.event_action=b.component_event.detail.eventName.toLowerCase();}
else if(b.component_event.detail.data.context=="dcof-error-tab"){b.event_label="dcof_material_search|errors";b.event_action=b.component_event.detail.eventName.toLowerCase();}}
if(b.component_event.detail.eventName=="focus input"){b.event_category="ti web component";b.event_action=b.component_event.detail.eventName;b.event_label=link_id+" "+b.component_event.detail.data.context.toLowerCase();b.event_value='1';}
if(b.component_event.detail.eventName=="filter"){b.event_category="ti web component";b.event_action=b.component_event.detail.eventName;b.event_label=link_id+" "+b.component_event.detail.data.filterColumn+'|'+b.component_event.detail.data.filterValue;b.event_value='1';}
if(b.component_event.detail.eventName=="focus quantity input"){b.event_category="ti web component";b.event_action=b.component_event.detail.eventName;b.event_label=link_id+" "+b.component_event.detail.context.toLowerCase();b.event_value='1';}
if(b.component_event.detail.eventName=="buy from distributor"){b.ti_gpn=b.component_event.detail.data.ti_gpn;b.ti_opn=b.component_event.detail.data.ti_opn;b.distributor_name=b.component_event.detail.data.distributor_name;b.sampleCheckoutType=b.component_event.detail.data.part_type;b.vBundleId=b.component_event.detail.data.vBundleId;if(typeof window.ti_addEvent=="function"){window.ti_addEvent(b,["conversion funnel","parts in carts"]);}}
if(b.component_event.detail.eventName=="chevron click"){b.event_category="ti web component";b.event_action=b.component_event.detail.eventName;b.event_label=link_id+" "+b.component_event.detail.data.column.toLowerCase()+" "+b.component_event.detail.data.value.toLowerCase();b.event_value='1';}
if(b.component_event.detail.eventName.toString().indexOf("modal close")>-1){b.event_category="ti web component";b.event_action=b.component_event.detail.eventName;b.event_label=link_id;b.event_value='1';}
if(b.component_event.detail.elementName.toString().toUpperCase().indexOf("TI-EXPANSION-PANEL")>-1){var panel_event_label=b.component_event.detail.elementName.toUpperCase()+"|"+link_id;link_id=b.component_event.detail.elementName.toUpperCase();b.event_category="ti web component";b.event_action=b.component_event.detail.eventName;b.event_label=panel_event_label;b.event_value='1';}
if(b.component_event.detail.eventName=="request sample"){b.sampleCheckoutType="sample";b.ti_opn=b.component_event.detail.data.ti_opn;b.ti_gpn=b.component_event.detail.data.ti_gpn;window.ti_addEvent(b,'sampleorbuy checkout');}
if(b.component_event.detail.eventName=="email validated"){window.ti_addEvent(b,['myti page email validated','conversion funnel']);}
if(b.component_event.detail.eventName=="email validated update"){window.ti_addEvent(b,'myti email validated update');}
if(b.component_event.detail.eventName=="login"){b.link_id="Log In";b.link_text="TI Login";window.ti_addEvent(b,'myti page existing login');}
if(b.component_event.detail.eventName=="create account"){b.link_id="Register and Continue";window.ti_addEvent(b,'myti page create account')}
if(b.component_event.detail.eventName=="select profile"){b.event_category="myTI";b.event_action=b.component_event.detail.eventName;b.event_label=b.component_event.detail.data.value.toLowerCase();b.event_value='1';}
if(b.component_event.detail.eventName=="add alert"){b.event_category="ti web component";b.event_action=b.component_event.detail.eventName;b.event_label=link_id+"|"+"add alert|"+b.component_event.detail.data.part_number.toLowerCase();b.event_value='1';b.ti_gpn=b.component_event.detail.data.part_number.toUpperCase();}
if(b.component_event.detail.eventName=="custom reel selection"){b.event_category="ti web component";b.event_action=b.component_event.detail.eventName;b.event_label=link_id+"|"+b.component_event.detail.context+"|"+b.component_event.detail.data.value;b.event_value='1';}
if(b.component_event.detail.eventName=="file browse"){b.event_category="ti web component";b.event_action=b.component_event.detail.eventName;b.event_label=link_id;b.event_value='1';}
if(b.component_event.detail.eventName.toString().indexOf("date code ")>-1){b.event_category="ti web component";b.event_action=b.component_event.detail.eventName;b.event_label=link_id+"|"+b.component_event.detail.context+"|"+b.component_event.detail.data.value;b.event_value='1';}
if(b.component_event.detail.elementName=="TI-DCOF-RESULTS"&&b.component_event.detail.eventName=="View Results"){b.events=["DCOF View Results"];b.dcofPartsSearched=b.component_event.detail.partsSearched;b.dcofPartsNotFound=b.component_event.detail.partsNotFound;b.dcofPartsSuggested=b.component_event.detail.partsSuggested;b.dcofPartsMatched=b.component_event.detail.partsSuccessfullyMatched;if(b.component_event.detail.maaName){b.dcofMaaName=b.component_event.detail.maaName;}}
if(b.component_event.detail.eventName=="Search"){if(b.component_event.detail.elementName=="TI-DCOF-SEARCH"){b.event_category="dcof-material search";b.event_action=b.component_event.detail.eventName.toLowerCase();b.event_label="parts";b.event_value='1';if(b.component_event.detail.maaName){b.dcofMaaName=b.component_event.detail.maaName;}}
else if(b.component_event.detail.elementName=="TI-DCOF-UPLOAD-LIST-MODAL"){b.event_category="dcof-material search";b.event_action=b.component_event.detail.eventName.toLowerCase();b.event_label="parts list";b.event_value='1';if(b.component_event.detail.maaName){b.dcofMaaName=b.component_event.detail.maaName;}}}
if(b.component_event.detail.eventName=="Sort"&&b.component_event.detail.elementName=="TI-DCOF-RESULTS-GRID"){b.event_category="ti web component";b.event_action=b.component_event.detail.eventName.toLowerCase();const after=b.component_event.detail.value.slice(b.component_event.detail.value.indexOf("|")+1).toLowerCase().trim()
const before=b.component_event.detail.value.slice(0,b.component_event.detail.value.indexOf("|")).toLowerCase().trim()
b.event_label=before+"|search_results|"+after
b.events=["dcof sort results"];}
if(b.component_event.detail.eventName=="Update ECCN HTS Field"&&b.component_event.detail.elementName=="TI-DCOF-RESULTS-GRID-ACTION-BAR"){b.event_category="dcof-material search";b.event_action=b.component_event.detail.eventName.toLowerCase();b.event_label=b.component_event.detail.value.toLowerCase();b.event_value='1';b.events=["dcof update eccn"];}
if(b.component_event.detail.eventName=="Click Remove One"&&b.component_event.detail.elementName=="TI-DCOF-RESULTS"){b.event_category="dcof-material search";b.event_action=b.component_event.detail.eventName.toLowerCase();b.event_label=b.component_event.detail.value.toLowerCase();b.event_value='1';b.events=["dcof remove one"];}
if(b.component_event.detail.eventName=="Click Remove All"&&b.component_event.detail.elementName=="TI-DCOF-ERROR-GRID"){b.event_category="dcof-material search";b.event_action=b.component_event.detail.eventName.toLowerCase();b.event_label="all";b.event_value='1';b.events=["dcof remove all"];}
if(b.component_event.detail.eventName=="Click See Suggestions"&&b.component_event.detail.elementName=="TI-DCOF-SUGGESTIONS-MODAL"){b.event_category="dcof-material search";b.event_action=b.component_event.detail.eventName.toLowerCase();b.event_label=b.component_event.detail.value.toLowerCase();b.event_value='1';b.events=["dcof see suggestions"];}
if(b.component_event.detail.eventName=="Click Suggestions Table"&&b.component_event.detail.elementName=="TI-DCOF-SUGGESTIONS-MODAL"){b.event_category="dcof-material search";b.event_action=b.component_event.detail.eventName.toLowerCase();b.event_label=b.component_event.detail.value.column.toLowerCase()+"|"+b.component_event.detail.value.partNumberSearched.toLowerCase();b.event_value='1';b.events=["dcof click suggestion table"];b.tcPartNumber=b.component_event.detail.value.OPN;b.product_id=b.component_event.detail.value.GPN;}
if(b.component_event.detail.eventName=="DCOF Select Suggestion"){b.event_category="dcof-material search";b.event_action="select suggestion";b.event_label=b.component_event.detail.value.partNumberSearched.toLowerCase();b.event_value='1';b.events=["dcof select suggestion"];b.tcPartNumber=b.component_event.detail.value.OPN;b.product_id=b.component_event.detail.value.GPN;}
if(b.component_event.detail.elementName=="TI-QUICK-ADD-TO-CART"){if(b.component_event.detail.eventName=="quick add to cart"){var express_opn=[];var express_quantity=[];var express_source=[];var express_carrier=[];var express_refnum=[];b.component_event.detail.data.partList.forEach(function(e){express_opn.push(e.opnId);express_quantity.push(e.quantity);express_source.push(e.tiAddtoCartSource);express_carrier.push(e.crOption);express_refnum.push(e.customRefNo);});b.event_category='store';b.event_action='add to cart';b.event_label=link_id+"|"+"quick add to cart";b.event_value='1';b.custom_metric_value='55';b.events=['add to cart'];b.ecom_event='add';b._cprod=b._cprodname=express_opn;b._cquan=express_quantity;b.cart_source=express_source;}else{b.event_category="ti web component";b.event_action=b.component_event.detail.eventName;b.event_label=link_id;b.event_value='1';}}
if(b.component_event.detail.elementName.toString().indexOf("TI-QRP")>-1){if(b.component_event.detail.eventName=="qrp results"){b.event_category="ti web component";b.event_action=b.component_event.detail.eventName;b.event_label=link_id;b.event_value='1';b.search_type='qrp tool';b.search_term=b.component_event.detail.data.value.length>1?b.component_event.detail.data.value.join("|"):b.component_event.detail.data.value[0];b.events=['internal searches'];b.custom_metric_value="7";}else if(b.component_event.detail.eventName=="qrp submit"){b.event_category="ti web component";b.event_action=b.component_event.detail.eventName;b.event_label=link_id;b.event_value='1';}else if(b.component_event.detail.eventName=="qrp download selected"){var loc="";if(path&&path[1].nodeName=="TD"){loc="qrp tool|results table "+b.component_event.detail.data.fileType+" "+b.component_event.detail.data.part_number[0];}else if(b['dom.pathname']=="/qrp/report"){loc="qrp report|individual part number "+b.component_event.detail.data.fileType+" "+b.component_event.detail.data.part_number[0];}else{loc="qrp tool|download selected "+b.component_event.detail.data.fileType;}
var part_list=b.component_event.detail.data.part_number.join("|");var filename=b.component_event.detail.data.part_number.length>1?"multiple":b.component_event.detail.data.part_number[0];b.tcPartNumber=part_list;b.event_category="ti web component";b.event_action=b.component_event.detail.eventName;b.event_label=loc;b.event_value='1';b.events=['quality data download','conversion funnel'];b.custom_metric_value="1";b.download_file_name="qrp-"+filename+"-"+b.component_event.detail.data.fileType;}else{b.event_category="ti web component";b.event_action=b.component_event.detail.eventName;b.event_label=link_id;b.event_value='1';}}
if(b.component_event.detail.elementName.toString().indexOf("TI-AVL-")>-1){if(b.component_event.detail.eventName=="view suggested part"||b.component_event.detail.eventName=="view alternate part"||b.component_event.detail.eventName=="view OPN alternates"){b.event_category="cross reference search";b.event_action=b.component_event.detail.eventName.toLowerCase();b.event_label=b.component_event.detail.value;b.event_value=1;b.distributor_name=b.component_event.detail.data.distributor_name.toLowerCase();b.mfgr_opn=b.component_event.detail.data.ti_opn;b.search_term=b.component_event.detail.data.search_term;b.search_type="cross reference search";b.avl_search_term=(b.component_event.detail.data.avl_search_term||'').toLowerCase();if(b.component_event.detail.eventName=="view OPN alternates"){b.event_label=b.component_event.detail.data.source_gpn.toLowerCase()+" | "+b.component_event.detail.data.source_opn.toLowerCase();b.mfgr_opn=b.component_event.detail.data.source_opn;}}else if(b.component_event.detail.eventName=="order now"){b.ti_opn=b.component_event.detail.data.ti_opn;b.tcPartNumber=b.component_event.detail.data.ti_opn;b.distributor_name=b.component_event.detail.data.distributor_name.toLowerCase();b.search_type="cross reference search";if(b.distributor_name=="ti store"||b.distributor_name=="texas instruments"){ti_addEvent(b,"order now");}}else if(b.component_event.detail.eventName=="select xref part"||b.component_event.detail.eventName=="select alternate part"||b.component_event.detail.eventName=="select OPN alternate"){b.event_category="cross reference search";b.event_action=b.component_event.detail.eventName.toLowerCase();b.event_label=b.component_event.detail.value;if(b.component_event.detail.eventName=="select OPN alternate"){b.event_label=(b.component_event.detail.data.alternate_type+"|"+b.component_event.detail.data.source_gpn+"|"+b.component_event.detail.data.source_opn+"|"+b.component_event.detail.data.mfgr_gpn+"|"+b.component_event.detail.data.mfgr_opn).toLowerCase();}
b.event_value=1;b.distributor_name=b.component_event.detail.data.distributor_name.toLowerCase();b.mfgr_opn=b.component_event.detail.data.mfgr_opn;b.search_term=b.component_event.detail.data.search_term;b.search_type="cross reference search";b.search_criteria=b.component_event.detail.data.search_criteria;b.data_source=b.component_event.detail.data.data_source;b.avl_search_term=(b.component_event.detail.data.avl_search_term||'').toLowerCase();}else if(b.component_event.detail.eventName=="select part category"){b.event_category="cross reference search";b.event_action=b.component_event.detail.eventName;b.event_label=b.component_event.detail.value;b.event_value=1;b.mfgr_opn=b.component_event.detail.data.ti_opn;b.search_type="cross reference search";}else if(b.component_event.detail.eventName.toString().indexOf("impression")>-1||b.component_event.detail.eventName.toString().indexOf("no result")>-1){b.event_category="cross reference search";b.event_action=b.component_event.detail.eventName;b.event_label=b.component_event.detail.value;b.event_value=1;b.search_criteria=b.component_event.detail.data.search_criteria;b.search_type="cross reference search";}else if(b.component_event.detail.eventName=='single part submit'||b.component_event.detail.eventName=='multiple part submit'||b.component_event.detail.eventName=='upload list filter'){b.event_category="cross reference search";b.event_action=b.component_event.detail.eventName;b.event_label=b.component_event.detail.data.value;b.event_value=1;}else if(b.component_event.detail.eventName=='avl_metrics_event_v2'){if(b.component_event.detail.data.metricsAction=='replace'||b.component_event.detail.data.metricsSourceOperation=='page-load'){b.event_category="cross reference search";b.event_action="view results";var partCharacteristics="ti_part|"+b.component_event.detail.data.metricsRowType;if(partCharacteristics.includes('cross')){partCharacteristics=partCharacteristics.replace('ti_part','competitor_part');}
else if(partCharacteristics.includes("not")||partCharacteristics.includes("hybrid")){partCharacteristics=partCharacteristics.replace('ti_part','unknown')}
b.event_label=b.component_event.detail.data.metricsSourceOperation.replace('-by','')+'|'+b.component_event.detail.data.metricsSearchTerm.toLowerCase()+'|'+partCharacteristics;b.search_criteria=b.component_event.detail.data.metricsCrossReferenceType||'';b.avl_search_term=b.component_event.detail.data.metricsSearchTerm.toLowerCase();b.distributor_name=b.component_event.detail.data.metricsFirstSelectedPartManuf.toLowerCase();b.tcPartNumber=b.component_event.detail.data.metricsMatchedPart;b.search_type="cross reference search";b.event_value=1;}}}
if(b.component_event.detail.elementName.toString().indexOf("TI-PPAP")>-1){b.event_category="ti web component";b.event_action=b.component_event.detail.eventName;b.event_label=typeof b.component_event.detail.data.ppap_request_num!=="undefined"?link_id+"|"+b.component_event.detail.data.ppap_request_num:link_id;b.event_value='1';b.ti_opn=typeof b.component_event.detail.data.ti_opn!=="undefined"?b.component_event.detail.data.ti_opn:"";if(b.component_event.detail.eventName=="ppap form submit"){delete b.event_category;delete b.event_action;}}
if(b.component_event.detail.eventName=="radio select"){if(b.component_event.detail.eventData){b.event_category="ti web component";b.event_action=b.component_event.detail.eventName;b.event_label=link_id+"|"+b.component_event.detail.eventData[0].radio_text+": "+b.component_event.detail.eventData[0].radio_state;b.event_value='1';}else{b.event_category="ti web component";b.event_action=b.component_event.detail.eventName;b.event_label=b.component_event.detail.data.context;b.event_value='1';}}
if(b.component_event.detail.eventName=="video initialized"){var videos=[];var videoElement=b.component_event.detail.data.context;var videoPlayerElement=videoElement.closest("ti-video-player");if(videoPlayerElement!==null&&videoPlayerElement.getAttribute("data-lid")===null){videoPlayerElement.setAttribute("data-lid",b.component_event.detail.elementName);}
videos.push(videoElement);attachVideoEvents(videos);}
if(b.component_event.detail.elementName.toString().toUpperCase().indexOf("TI-IMAGE-COMPARISON")>-1){link_id=link_id!=='undefined'?link_id+"|":"";b.event_category="ti web component";b.event_action=b.component_event.detail.eventName;b.event_label=link_id+b.component_event.detail.data.image1+" "+b.component_event.detail.data.image1;b.event_value='1';}
var seamlessCheckoutEvents=["remove from cart","select carrier option","order placed","checkout select","checkout step","checkbox click","change currency impression"]
if(seamlessCheckoutEvents.includes(b.component_event.detail.eventName)){b.event_category="ti web component";b.event_action=b.component_event.detail.eventName;b.event_value=1;switch(b.component_event.detail.eventName){case"remove from cart":b.event_label=b.component_event.detail.data.context.join("_");b.event_value=b.component_event.detail.data.context.length;break;case"order placed":b.event_label=b.component_event.detail.data.addressType+"|"+b.component_event.detail.data.profile
break;case"change currency impression":b.event_non_interaction=1;b.event_label=link_id+"|"+b.component_event.detail.data.context;break;default:b.event_label=link_id+"|"+b.component_event.detail.data.context
break;}}
if(b.component_event.detail.eventName.toLowerCase().indexOf("document center")>-1){if(b.component_event.detail.eventName=="document center upload"&&b.component_event.detail.status&&b.component_event.detail.status=="READY"){link_id=b.component_event.detail.data.source+"|"+b.component_event.detail.data.tags.map(e=>e.tagName).join("_");b.event_category="ti web component";b.event_action=b.component_event.detail.eventName+" success";b.event_label=link_id+"|"+b.component_event.detail.data.type;b.event_value='1';}else if(b.component_event.detail.eventName=="document center upload"&&b.component_event.detail.status&&b.component_event.detail.status=="ERROR"){b.event_category="ti web component";b.event_action=b.component_event.detail.eventName+" error";b.event_label=b.component_event.detail.error;b.event_value='1';}}
if(b.component_event.detail.eventName=="cue card impression"){b.event_category="ti web component";b.event_action=b.component_event.detail.eventName;b.event_label=b.component_event.detail.data.context;b.event_value='1';}
if(b.component_event.detail.eventName=="backlog report subscription"){if(b.component_event.detail.status=="READY"){b.event_category="ti web component";b.event_action=b.component_event.detail.eventName;b.event_label=b.component_event.detail.data.frequency;b.event_value='1';}}}
b.ga4_link_id=b.event_label;if(b.event_label.replace(link_id,'').startsWith(' ')){b.ga4_link_text=b.event_label.replace(link_id,'').trim();}else if(b.event_label.replace(link_id,'').startsWith('|')){b.ga4_link_text=b.event_label.replace(link_id,'').replace('|','');}else if(b.event_label.replace(link_id,'').endsWith('|')){b.ga4_link_text=b.event_label.replace(link_id,'').replace(/|$/,'');}else{b.ga4_link_text=b.event_label.replace(link_id,'');}
b.ga4_link_class=link_id;b.ga4_event_name=b.event_action;}}}}catch(e){utag.DB(e)}},function(a,b){if(b['video_event']){if(b['video_event']=='video_start'){ti_addEvent(b,'conversion funnel');}
b['video_event']=b['video_event'].replace(/\_/g,' ');b['videoTimeStamp']=b['page_timestamp']||utag_data['page_timestamp'];ti_addEvent(b,b['video_event']);manualLog('Add video event": '+b['video_event'],'video');}
if(b['ev_action']&&b['ev_action'].indexOf('ab test')==-1){ti_addEvent(b,'personalization');}
if(b['link_text']&&!b['link_id']){if(b['activityPromoID']){b['promo_id']=b['activityPromoID'];ti_addEvent(b,'activity promo impression');}else if(b['homepagePromoID']){b['promo_id']=b['homepagePromoID'];ti_addEvent(b,'homepage promo impression');}else if(b['productPromoID']){b['promo_id']=b['productPromoID'];ti_addEvent(b,'product promo impression');}}
if(b['event_category']){if(b['event_category']=='links'&&b['download_file_name']){ti_addEvent(b,'file downloads');}
if(b['event_category']=='promo'&&b['event_action']&&b['event_action'].indexOf('click')>-1){ti_addEvent(b,'promo click');}
if(b['event_category']=='store'&&b['event_action']=='add to cart'){ti_addEvent(b,'add to cart');}
if(b['event_category']=='ti web component'&&b['event_action']=='remove from cart'){ti_addEvent(b,'remove item');}}
if(b['oct_eventName']){if(b['oct_eventName']=='Link Track'){ti_addEvent(b,'custom link track');}
if(b['oct_eventName']=='selection tool link click'){ti_addEvent(b,'selection tool link click');}
if(b['oct_eventName']=='comparison tool link click'){ti_addEvent(b,'comparison tool link click');}
if(b['oct_eventName']=='ODS Search'){ti_addEvent(b,'search type');}
if(b['oct_eventName']=='search'){if(b['search_type']&&b['search_type'].indexOf('tidesigns')>-1){ti_addEvent(b,'reference design search');}else{ti_addEvent(b,'search type');}}
if(b['oct_eventName']=='selection tool search'){ti_addEvent(b,['selection tool search','conversion funnel']);}
if(b['oct_eventName']=='null search'){ti_addEvent(b,['null search','internal searches']);}
if(b['oct_eventName']=='Data Converter'){ti_addEvent(b,'data converter');}
if(b['oct_eventName']=='Companion Parts'){ti_addEvent(b,'companion parts');}
if(b['oct_eventName']=='Community Participation'){ti_addEvent(b,['community participation','conversion funnel']);}}
if((b['dom.pathname'].match(/\/lsds\/ti.*/gi)!==null||b['isTrainingPortal']=='yes'||b['pageType']=="portal")&&a=='view'){utag_data['events']=ti_addEvent(b,['portal page view','conversion funnel']);}
if((b["dom.pathname"]=="/qrp/report"||b["dom.pathname"]=="/quality-reliability-packaging-download/report")&&b["ut.event"]=="view"){ti_addEvent(b,"quality data view");b.tcPartNumber=window.partNum}
var internalSearchEvents=b.events.toString().match(/internal searches|null search|reference design search|search type|DCOF View Results/g);var manualMetric=b['custom_metric_value']=='7';var specialCase=b.events.toString().indexOf('selection tool search')>-1&&(!b['non_search_init']||b['non_search_init']&&b['non_search_init']=="");if(internalSearchEvents||manualMetric||specialCase){var searchTypes=(b['search_type']||'')+(b['referring_search_type']||'');if(searchTypes.indexOf('st:')>-1){b.events=ti_addEvent(b,'selection tool search conversion');}
else if(searchTypes.indexOf('cross reference')>-1){b.events=ti_addEvent(b,'bom xref search');}}
if(b['event_category']=='design tools'&&b['event_action']=='tirex page view'){b.events=ti_addEvent(b,'tirex page view');}},function(a,b){try{if(1){var is_GA4=u.id!=undefined&&u.id=='318';var enable=(new Date()>new Date(2024,0,1))||(utag_data['cp.2024Conversions']=='true')||(is_GA4);if(enable){b.events=ti_removeEvent(b,'conversion funnel');b['conversion_funnel']='';b['total_conversions']=0;b['conversion_event']='';if(b['events']!=undefined&&b['events'].indexOf('3p tool folder views')>-1){b.events=ti_removeEvent(b,'hardware folder views');}
if(b['events']!=undefined&&b['events'].indexOf('sw folder views')>-1){b.events=ti_addEvent(b,'tool folder views');}
if(typeof b['events']!=undefined){arr_of_events=b['events'];}
if(typeof arr_of_events!='undefined'){var eventName;var eventLen=arr_of_events.length;var funnelName='n/a';var trigger='yes';var ga4_event_array=b['ga4_event_array']||[];if(eventLen>0){for(i=0;i<eventLen;i++){eventName=arr_of_events[i];var funnelName='n/a';var trigger='yes';switch(eventName){case'product folder views':case'solution folder views':case'portal page view':case'corporate blog views':case'technical article view':case'design guide views':case'white paper views':case'application note views':case'selection tool search':funnelName="interest";conversionName=eventName.replace(/\s/g,'_');if(conversionName.slice(-1)=='s'){conversionName=conversionName.slice(0,-1);}
break;case'video start':funnelName='interest';conversionName='video_view';break;case'myti page email validated':funnelName='interest';conversionName='myti_registration_validated';break;case'hardware folder views':funnelName='interest';conversionName='tool_hardware_development';break;case'reference design folder view':funnelName='interest';conversionName='tool_reference_designs';break;case'design and simulation folder views':funnelName='interest';conversionName='tool_design_and_sim';break;case'sw folder views':funnelName='interest';conversionName='tool_software_development';break;case'3p hardware':funnelName='interest';conversionName='third_party_tool_hardware_development';break;case'3p software':funnelName='interest';conversionName='third_party_tool_software_development';break;case'3p reference':funnelName='interest';conversionName='third_party_tool_reference_designs';break;case'3p design and sim':funnelName='interest';conversionName='third_party_tool_design_and_sim';break;case'bom xref search':case'datasheet view':case'clock tree create design':case'filter design create design':case'coil designer create design':case'ultra evm create design':case'webench create design':case'tirex page view':case'product details views':case'timss create design':funnelName='consideration';conversionName=eventName.replace(/\s/g,'_');if(conversionName.slice(-1)=='s'){conversionName=conversionName.slice(0,-1)}
break;case'automotive ppap submit':funnelName='consideration';conversionName='automotive_ppap_submit_valid';break;case'cad/cae symbol download':funnelName='consideration';conversionName='cad_cae_symbol_download';break;case'community views':funnelName='consideration';conversionName='e2e_views';break;case'community participation':funnelName='consideration';conversionName='e2e_participation';break;case'quality data download':funnelName='consideration';conversionName='qrp_download';break;case'parts in carts':funnelName='conversion';conversionName='disti_buy_handoff';break;case'sample orders':funnelName='consideration';conversionName='sample_order';trigger='no';break;case'paid ic orders':funnelName='conversion';conversionName='ic_order';trigger='no';break;case'tool orders':funnelName='conversion';conversionName='evm_purchase';trigger='no';break;default:}
if(funnelName!='n/a'&&b['conversion_event'].indexOf(eventName)<0){b.events=ti_addEvent(b,'conversion funnel');b['total_conversions']=b['total_conversions']+1;b['conversion_funnel']=funnelName;b['conversion_event']=b['conversion_event']+eventName;b['conversion_name']=conversionName;utag_data['conversion_funnel']=funnelName;utag_data['conversion_event']=utag_data['conversion_event']+eventName;utag_data['conversion_name']=conversionName;if(b['ut.event']!=null&&b['ut.event']=="view"&&trigger=='yes'){ga4_event_array.push(conversionName);b['ga4_event_array']=ga4_event_array;}
else if(b['ut.event']!=null&&b['ut.event']=="link"&&trigger=='yes'){b.ga4_event_name=conversionName;}
if(is_GA4&&b['event_value']==undefined){mapFunc([conversionName],u.data,{'value':1});}
if(b['ut.event']!=null&&b['ut.event']=='link'){break;}}}}}}}}catch(e){utag.DB(e)}},function(a,b){try{if(1){if(b['ut.event']=="link"&&b['ev_action']&&b['ev_action'].length>0){if(b['ev_intc']){b.internal_campaigns=b['ev_campaign'].toLowerCase();b.internal_campaign_source='internal';b.internal_campaign_medium='evergage';b.internal_campaign_term=b['ev_name'].toLowerCase();b.internal_campaign_content=b['ev_user'].toLowerCase();if(typeof b.internal_campaigns!=='undefined'&&b.internal_campaigns.length>0){var intcArry=[];intcArry.push(b.internal_campaigns.toLowerCase());intcArry.push(b.internal_campaign_source.toLowerCase());intcArry.push(b.internal_campaign_medium.toLowerCase());intcArry.push(b.internal_campaign_term.toLowerCase());intcArry.push(b.internal_campaign_content.toLowerCase());window.tl_setCookie('ga_intc',intcArry);utag_data['cp.utag_main_intc']=intcArry;utag.data['cp.utag_main_intc']=intcArry;}}
window._ev_sent_arry=window._ev_sent_arry||[];if(b['ev_action'].indexOf('impression')>-1){window._ev_sent_arry.push(b['ev_campaign']+"i")}else{window._ev_sent_arry.push(b['ev_campaign']+"c")}}}}catch(e){utag.DB(e)}},function(a,b){try{if(1){if((typeof b['isBot']!=='undefined'&&b['isBot']=='1')&&(typeof b['qp.load_decibel']=='undefined'||(typeof b['qp.load_decibel']!=='undefined'&&b['qp.load_decibel']!=='true'))){return false;}
b['all_contentGroups']=b['contentGroup5']||b['contentGroup4']||b['contentGroup3']||b['contentGroup2']||b['contentGroup1']||'';var host=document.location.hostname;if(host=='www.ti.com'||host=='www.tij.co.jp'||host=='www.ti.com.cn'||host=='bomcross.ti.com'||host=='dev.ti.com'||host=='tisamples.ti.com'||host=='samples.ti.com'||host=='e2e.ti.com'||host=='e2echina.ti.com'||host=='software-dl.ti.com'||host=='webench.ti.com'||host=='training.ti.com'||host=='careers.ti.com'||host=='news.ti.com'||host=='ko-kr.news.ti.com'||host=='ja-jp.news.ti.com'||host=='zh-tw.news.ti.com'||host=='de-de.news.ti.com'||host=='news.ti.com.cn'||host=='news.tij.co.jp'||host=='investor.ti.com'||host=='login.ti.com'||host=='support.ti.com'){utag_data['di_property_id']='254679';b['di_property_id']='254679';}else{utag_data['di_property_id']='255114';b['di_property_id']='255114';}
if(typeof b['ut.event']!=='undefined'&&b['ut.event']!=='view'){_trackDecibelGoal(b['ut.event'],b['events'],b);}}}catch(e){utag.DB(e)}},function(a,b){try{if(1){if(b['ut.event']=="link"&&b.component_event){if(b.component_event.detail.eventName=="qrp results"){_tiAnalyticsTrack('decibelInsight','formSubmitted','[data-di-form-id = "qrp-form"]');_tiAnalyticsTrack('decibelInsight','trackPageView','/qrp/results');}else if(b.component_event.detail.eventName=="qrp-error-correct"){_tiAnalyticsTrack('decibelInsight','trackPageView','/qrp/error-correct');}}}}catch(e){utag.DB(e)}}];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f;u.data={"qsp_delim":"&","kvp_delim":"=","base_url":"https://cdn.decibelinsight.net/i/##utag_account##/di.js","da_accountId":"13876","da_propertyId":"","di":"decibelInsight"};for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){if(typeof utag_err!='undefined'){utag_err.push({e:'extension error:'+e,s:utag.cfg.path+'utag.'+id+'.js',l:c,t:'ex'})}}};for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.data[e[f]]=b[d];window._da_[e[f]]=b[d];}}}
if(!u.initialized){u.initialized=true;window._da_.oldErr=window.onerror;window._da_.err=[];window.onerror=function(){_da_.err.push(arguments);_da_.oldErr&&_da_.oldErr.apply(d,Array.prototype.slice.call(arguments));};window.DecibelInsight=u.data.di;window[u.data.di]=window[u.data.di]||function(){(window[u.data.di].q=window[u.data.di].q||[]).push(arguments);};if(u.data.da_accountId){if(u.data.da_propertyId){u.data.base_url="https://cdn.decibelinsight.net/i/##utag_account##/##utag_property##/di.js";u.data.base_url=u.data.base_url.replace("##utag_property##",u.data.da_propertyId);}
u.data.base_url=u.data.base_url.replace("##utag_account##",u.data.da_accountId);u.loader({"type":"script","src":u.data.base_url,"cb":null,"loc":"script","id":"utag_221"});}else{utag.DB("Tag 221 - Missing Account ID");}}
}};utag.o[loader].loader.LOAD(id);}("221","ti.main"));}catch(error){utag.DB(error);}
