# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.com_port = QtWidgets.QComboBox(self.groupBox)
        self.com_port.setObjectName("com_port")
        self.horizontalLayout.addWidget(self.com_port)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.baud_rate = QtWidgets.QComboBox(self.groupBox)
        self.baud_rate.setObjectName("baud_rate")
        self.baud_rate.addItem("")
        self.baud_rate.addItem("")
        self.baud_rate.addItem("")
        self.horizontalLayout.addWidget(self.baud_rate)
        self.connect_btn = QtWidgets.QPushButton(self.groupBox)
        self.connect_btn.setObjectName("connect_btn")
        self.horizontalLayout.addWidget(self.connect_btn)
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.x_label = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.x_label.setFont(font)
        self.x_label.setObjectName("x_label")
        self.verticalLayout_2.addWidget(self.x_label)
        self.y_label = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.y_label.setFont(font)
        self.y_label.setObjectName("y_label")
        self.verticalLayout_2.addWidget(self.y_label)
        self.horizontalLayout_2.addWidget(self.groupBox_2)
        self.plot_widget = QtWidgets.QGraphicsView(self.centralwidget)
        self.plot_widget.setMinimumSize(QtCore.QSize(400, 300))
        self.plot_widget.setObjectName("plot_widget")
        self.horizontalLayout_2.addWidget(self.plot_widget)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.raw_display = QtWidgets.QTextEdit(self.groupBox_3)
        self.raw_display.setReadOnly(True)
        self.raw_display.setObjectName("raw_display")
        self.verticalLayout_3.addWidget(self.raw_display)
        self.log_display = QtWidgets.QTextEdit(self.groupBox_3)
        self.log_display.setMaximumHeight(60)
        self.log_display.setReadOnly(True)
        self.log_display.setObjectName("log_display")
        self.verticalLayout_3.addWidget(self.log_display)
        self.verticalLayout.addWidget(self.groupBox_3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "蓝牙AOA定位系统"))
        self.groupBox.setTitle(_translate("MainWindow", "串口配置"))
        self.label.setText(_translate("MainWindow", "COM端口:"))
        self.label_2.setText(_translate("MainWindow", "波特率:"))
        self.baud_rate.setItemText(0, _translate("MainWindow", "9600"))
        self.baud_rate.setItemText(1, _translate("MainWindow", "115200"))
        self.baud_rate.setItemText(2, _translate("MainWindow", "230400"))
        self.connect_btn.setText(_translate("MainWindow", "连接串口"))
        self.groupBox_2.setTitle(_translate("MainWindow", "实时坐标"))
        self.x_label.setText(_translate("MainWindow", "X: 0.00 m"))
        self.y_label.setText(_translate("MainWindow", "Y: 0.00 m"))
        self.groupBox_3.setTitle(_translate("MainWindow", "原始数据"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
